### ISSUE TITLE
"jsQR.min.js" is constantly reloaded

### ISSUE THREAD

**Issue by pugmas** [BlackBoxVision/react-qr-reader#1] opened 2020-04-09 18:50 UTC
Hi!
With your demo and my test code "jsQR.min.js" is constantly reloaded from "cdn.jsdelivr.net". 
Why not put "jsqr" to dependencies? Like JodusNodus/react-qr-reader does?

**Comment by JonatanSalas** [comment] 2020-04-09 19:22
@pugmas we're currently using a react-hook called [`useWorker`](https://useworker.js.org/) to create a Web Worker and calling it using a Promise based API. It seems that this library recreates the blob related to the Web Worker on each worker call. 

Currently we're looking into submitting a PR for caching dependencies or avoid blob regeneration.

**Comment by JonatanSalas** [comment] 2020-04-11 18:03
@pugmas I've open an issue to understand if this is an intended behavior for the lib, in case of not, I will work on improving it. 

https://github.com/alewin/useWorker/issues/33

**Comment by JonatanSalas** [comment] 2020-04-12 22:17
@pugmas the lib creator has done a PR with a fix for this. 

https://github.com/alewin/useWorker/pull/34

When this PR is closed and a new version is released we'll update the lib version so this is fixed.

**Closed** 2020-08-26 11:03 UTC

**Comment by JonatanSalas** [comment] 2020-08-26 11:05
@pugmas the bug is currently solved, you can check this fix by running the following script:

```bash
npm i --save @blackbox-vision/react-qr-reader@1.0.0
```
